/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialMediaPlatform } from "./SocialMediaPlatform";
export * as factories from "./factories";
export { SocialMediaPlatform__factory } from "./factories/SocialMediaPlatform__factory";
